### ISSUE TITLE
Urgent Update: Wownero Vulnerability Fixed

### ISSUE THREAD

**Issue by wowario** [cypherstack/stack_wallet#1054]
Rucknium at Monero Research Labs reported a [vulnerability with Wownero's decoy selection algorithm vulnerability](https://codeberg.org/wownero/wownero/issues/488). 

The issue has been fixed and it is recommended that wallets update ASAP to the latest Wownero version, [v0.11.3.0](https://codeberg.org/wownero/wownero/releases/tag/v0.11.3.0).

**Comment by sneurlax** [comment]
This has now been fixed.
