### ISSUE TITLE
Stack restore hangs

### ISSUE THREAD

**Issue by danrmiller** [cypherstack/stack_wallet#109]
Invalid argument (name): No Coin enum value with that prettyName: "bitcoincashTestnet"
#0      coinFromPrettyName (package:stackwallet/utilities/enums/coin_enum.dart:225)
#1      SWB._restoreNodes (package:stackwallet/pages/settings_views/global_settings_view/stack_backup_views/helpers/restore_create_backup.dart:1179)
<asynchronous suspension>
#2      SWB._restoreEverythingButWallets (package:stackwallet/pages/settings_views/global_settings_view/stack_backup_views/helpers/restore_create_backup.dart:488)
<asynchronous suspension>
#3      SWB.restoreStackWalletJSON (package:stackwallet/pages/settings_views/global_settings_view/stack_backup_views/helpers/restore_create_backup.dart:593)
<asynchronous suspension>
#4      _StackRestoreProgressViewState._restore (package:stackwallet/pages/settings_views/global_settings_view/stack_backup_views/sub_views/stack_restore_progress_view.dart:107)
<asynchronous suspension

**Comment by rehrar** [comment]
Fixed.
