### ISSUE TITLE
[Bug] Black screen freezing

### ISSUE THREAD

**Issue by nahuhh** [cypherstack/stack_wallet#114]
Android 10

Often the app will freeze and switching apps will show it as a black screen.
Reproducible. You just need to be messing around in the different setting screens until it locks up.

Sometimes ghost images.

![Image_236.jpg](https://user-images.githubusercontent.com/50635951/193475300-21f6df3d-32de-4d7d-a1c0-b5fbaf08d3a4.jpg)

**Comment by rehrar** [comment]
Does this still happen?

**Comment by nahuhh** [comment]
Im able to get a black screen via changing nodes shortly after opening a monero wallet

Bouncing through settings causing the ghosting seems to be fixed

**Comment by rehrar** [comment]
Can't reproduce. Can reopen if it keeps happening.

**Comment by nahuhh** [comment]
Apologies
Forgot to update. Seems to have been fixed in one of the updates
