### ISSUE TITLE
[Request] Send/Receive EPIC using https method

### ISSUE THREAD

**Issue by mvozzo** [cypherstack/stack_wallet#169]
The EPIC Desktop GUI Wallet has the ability to send/receive funds via https:// method (see below)

![Epic-GUI-Send-screen](https://user-images.githubusercontent.com/10014870/197123559-ff6daf61-90c2-40cd-9a53-91bf10ee5d39.jpg)

You can download the EPIC Wallet via this link to check it out for yourself - https://github.com/EpicCash/epic-gui-wallet

Please enable Stack Wallet to support this method of transfer so that we can send EPIC back/forth between EPIC GUI Wallet and Stack Wallet.

**Comment by rehrar** [comment]
Sending via https works. Receiving is off the table for now given how you would need to run a server on your phone temporarily and that's not something easily done.

**Comment by mvozzo** [comment]
Thanks for the update @rehrar.  I really love Stack Wallet - Well Done!
