### ISSUE TITLE
Crash during wallet creation. 

### ISSUE THREAD

**Issue by bch-infraspace** [cypherstack/stack_wallet#170]
App crashes every time I enter my PIN for the second time. Immediately after entering the fourth digit, before tapping Next.

Galaxy S7
Android 8.0.0

**Comment by rehrar** [comment]
Can we get some more info? Which wallet were you making? And if it still occurs, can you paste the Copied Info Debug Logs here?

**Comment by bch-infraspace** [comment]
It's the Getting Started process so it doesn't say yet which wallet is
being created exactly. There's no option to skip so I can't enable any
debugging and have no idea where logs would be.

It happens whether I select "Easy crypto" or "Incognito".

It's been updated a couple of times via Fdroid and is currently version
1.5.17.

**Comment by rehrar** [comment]
Hello. Is this still an issue? Android 8 might be too old.

**Comment by bch-infraspace** [comment]
Yes. Still happens every time.

**Comment by sneurlax** [comment]
I was not able to reproduce this issue.

**Comment by rehrar** [comment]
Once more can I ask you to see if this persists? If so we'll look into it now that we've exited beta. @bch-infraspace

**Comment by bch-infraspace** [comment]
I've since moved on to a different make and model which works perfectly. Android v 12

**Comment by rehrar** [comment]
Wonderful! Thanks for letting us know.
