### ISSUE TITLE
[Request] Please consider adding Ycash ($YEC) Privacy Coin

### ISSUE THREAD

**Issue by mvozzo** [cypherstack/stack_wallet#171]
Please consider adding Ycash ($YEC) which is a hard fork of the popular privacy coin - Zcash ($ZEC) but with a big different in the distribution mechanism, they have set aside 5% of mined $YEC for their Ycash Development Fund.

Homepage - https://y.cash/
Block Explorer - https://yecblockexplorer.com/
Full Node YEC Wallet - https://github.com/ycashfoundation/yecwallet/releases
They do have a mobile wallet called YWallet ( https://ywallet.app/ ), however, I think Stack Wallet is far superior easier to use interface. 
Btw, YEC support a secure privacy messenger service (you can learn about it here - https://youtu.be/3fhn7xV534A?t=52

Just a thought.

**Comment by rehrar** [comment]
@mvozzo you think you can drum up some buzz in the YEC community to see if t his is something they'd be excited for?

**Comment by mvozzo** [comment]
Thanks for the reply @rehrar ,  I shall post the question on forum and start a discussion around it.  Will let you know if there is strong interest.  Thanks for the consideration.

**Comment by mvozzo** [comment]
I have contacted some folks in the YEC community and they seem to be very content with their recently released YEC Wallet. 
Their wallet protection is great and it can be used to store both $YEC and $ZEC (Zcash). or some other coin  
It does have and pretty awesome "Feature call : Secure & Private Messaging via YEC."
It's pretty cool I must admit.  
   
Website  -  https://ywallet.app/  
Flathub Install Info - https://flathub.org/apps/details/app.ywallet.Ywallet

I'm happy for this idea to be put on the back burner so that you dev team can focus on more pressing issues.

**Comment by nahuhh** [comment]
@rehrar  close

**Comment by danrmiller** [comment]
ok
