### ISSUE TITLE
A lot of critial issues...

### ISSUE THREAD

**Issue by wzykubek** [cypherstack/stack_wallet#224]
I observed many issues after using wallet for only one hour.

- Cannot import 24 word seed for Bitcoin and Litecoin. Wallet highlights all words to green color, but after all it says the seed phrase is incorrect. Any other wallet importing these phrases correctly.
- Freezes when wallet is open for few minutes and user is AFK. After clicking on the random place, the screen is black and app needs to be restarted.
- Wownero blockchain isn't syncing. It stops at the random moment and randomly goes to 99,XX% which isn't correct, because wallet doesn't show any of transactions on the blockchain.

I cannot even use that wallet, when I cannot restore any of my previously created... 

version: 1.5.17

**Comment by rehrar** [comment]
Hello, can we have the platform, OS version, and device that you're using?

**Comment by samedamci** [comment]
Android 11 on realme 8

**Comment by rehrar** [comment]
Hello, is this still the case?

**Comment by rehrar** [comment]
Will reopen if this is still the case, but closing for now.
