### ISSUE TITLE
Issue sending EPIC to Stack Wallet from Vite Wallet - Receipt address is invalid

### ISSUE THREAD

**Issue by mvozzo** [cypherstack/stack_wallet#229]
Hi Stack Wallet Dev Team, 
I'm trying to send EPIC Cash from my Vite Wallet ( https://vite.org ) to Stack Wallet as I much prefer the Stack Wallet interface which is simpler and cleaner - well done! 

**HERE IS THE PROBLEM:**
I open Stack Wallet and have the "Receive" QR code on-screen. 
When I try scanning the QR code when in Vite Wallet, the QR code is unable to be read. (1st red flag)

I then proceed to copy-n-paste the Epic Wallet Receive Address from Stack Wallet to Vite Wallet. 
Upon hitting the Send button I get this Error message: "Wrong Address! Please check the format". (2nd red flag) 

Please confirm if there is an issue with the EPIC Cash QR code and Receive Addresses generated by Stack Wallet? 

If by chance, EPIC coins can only be transferred between Stack Wallets users, then can you please make this limitation more obvious to the user via some message on the Send/Receive screens. 

Many Thanks and keep up the good work.

**Comment by danrmiller** [comment]
Thank you, Stack Wallet EPIC Cash addresses currently won't work to receive from other implementations and services such as Vite. You can however send from Stack Wallet to any standard EPIC Cash http receiver such as Vite. And thank you for the feedback that this should be clearly specified on the send and receive screen, I am passing that along.

**Comment by mvozzo** [comment]
Thanks @danrmiller for the reply. 
I am just wondering how do I deposit EPIC into Stack Wallet? 
On one of my other threads it mentioned a server needed to be running on a mobile device inorder to be able to recieve funds into the wallet from Epic Desktop GUI wallet. So I am a little confused as to how to recieve EPIC in Stack Wallet.

**Comment by danrmiller** [comment]
@mvozzo So right now the best way will probably be to import the seed from a wallet that has funds.
