### ISSUE TITLE
[Feature Request] Add Fulcrum server support for Bitcoin nodes

### ISSUE THREAD

**Issue by InnocuousFinch** [cypherstack/stack_wallet#233]
[Fulcrum](https://github.com/cculianu/Fulcrum) is currently the most performant implementation of Electrum Server currently available for Bitcoin. Would be great to see Stack Wallet support Fulcrum.

**Comment by molecular** [comment]
Not just for Bitcoin:

> A fast & nimble SPV server for Bitcoin Cash, Bitcoin BTC, and Litecoin.

(https://github.com/cculianu/Fulcrum)

**Comment by InnocuousFinch** [comment]
This is working for me now. Not sure if a change was actually implemented or not. But can probably close this issue.

**Comment by molecular** [comment]
Well, I guess fulcrum speaks the electrum server protocol, right? So it's transparent to the client wether it's talking to a electrumx, fulcrum or whatever other server it's talking to.

I'm not sure wether fulcrum adds anything on top of the standard that could be used, though.

@cculianu <- I guess I can't ping the fulcrum dev like this, can I?

**Comment by InnocuousFinch** [comment]
Didn't see anything here as far as fixes but Fulcrum is working great for BTC now.

**Comment by molecular** [comment]
> Didn't see anything here as far as fixes but Fulcrum is working great for BTC now.

There wasn't any fix needed. 

Stackwallet uses my fulcrum server (and others) just fine for Bitcoin Cash (BCH) and it has been like this at the time of your issue creation.
