### ISSUE TITLE
[FEATURE REQUEST] Send/Recieve EPIC via File Transfer Method

### ISSUE THREAD

**Issue by mvozzo** [cypherstack/stack_wallet#235]
Please consider allowing EPIC to be Sent/Recieved using the same method used in the Open Source EPIC Desktop GUI Wallet via File Transfer . 

This will negate the need for running a server on the mobile device, as was outlined by @rehrar on my other ticket. 

You can download the EPIC Desktop GUI Wallet via this link to check it out for yourself - https://github.com/EpicCash/epic-gui-wallet

Please enable Stack Wallet to support this method of transfer so that we can send EPIC back/forth between EPIC GUI Wallet and Stack Wallet.

**Comment by rehrar** [comment]
After some consideration, I have decided not to support this for now, so as not to confuse new users. Ultimately I just think interactivity makes things too difficult for the average user, who is the target audience of Stack.
