### ISSUE TITLE
Incorrect transaction details on Wownero and sent amount did not appear on the receiving address.

### ISSUE THREAD

**Issue by KayzIzlynn** [cypherstack/stack_wallet#241]
**Summary:**
1) I have 2 Wownero wallets
2) Transferred some amount from wallet A to wallet B.
3) Did not receive the amount transferred.

**Wownero wallet A transaction details:** 
**Sent**: 25 Nov 2022, 04:39 am

**Wownero wallet B transaction details:** 
**Sent**: 25 Nov 2022, 04:39 am
 
Wownero wallet B transaction detail should appear as "Received" instead of "Sent".

![Wownero 1](https://user-images.githubusercontent.com/116454402/204161216-3196750f-1f1c-4ce9-8376-720ff9b7cb9a.jpg)

![Wownero 2](https://user-images.githubusercontent.com/116454402/204161384-98dc54b8-db41-42c6-b96a-2eaeb3dcb05e.jpg)

**Comment by nahuhh** [comment]
It appears you have restored the same wallet twice.

If the wallets are identical (same seed), then
1. Wallet b will show the correct balance after confirmation
2. Wallet a knows the correct balance because it created the tx

If 1 doesnt work = bug

**Comment by rehrar** [comment]
Should be fixed.
