### ISSUE TITLE
Wallet deletion incorrectly says "You will also be asked to verify the words on the next screen." but you are not asked to verify.

### ISSUE THREAD

**Issue by danrmiller** [cypherstack/stack_wallet#244]
When choosing to delete a wallet, the required View Backup Key screen says "You will also be asked to verify the words on the next screen." but you are actually not asked to verify, probably this screen is re-used with this text from wallet creation.

**Comment by rehrar** [comment]
Change to "You will be shown your recovery phrase on the next screen."
