### ISSUE TITLE
[FEATURE REQUEST] Add the option to "Generate New Address" for Wallet-to-Wallet transfers.

### ISSUE THREAD

**Issue by mvozzo** [cypherstack/stack_wallet#253]
Hi Stack Wallet Team, I ❤️ this wallet, it's so easy to use.  

In the "Send To" address there's the option to select one of my other wallets under "My Stack Favorites".
This is a brilliant 💡 as it saves me time and prevents human error via copy-n-paste. My idea below expands on this functionality.

**FEATURE REQUEST: EXTRA PRIVATE MODE** for Wallet-to-Wallet transfers
As Stack Wallet prides itself as a Privacy Wallet, a way to improve privacy for wallet-to-wallet transfers is to give the user the option to "Generate New Deposit Address".  I realise not all coins support this, but many of the coins in Stack Wallet do such as Wownero, Doge, Monero and other.  
  
When this option is activated, Stack Wallet will generate a New address in the destination wallet and then send the coins to the freshly created address. This saves the user a lot of time. No more messing around going into different wallets to generate a new receive address the saving to the address book before doing transactions.  

This feature will add an additional layer of privacy for Wallet-to-Wallet transfers and I've seen this functionality in other mobile wallets that I've used. Hence, this could be a potential 1st for Stack Wallet.

**Comment by nahuhh** [comment]
Stack already generates a fresh subaddress

**Comment by sneurlax** [comment]
> Stack already generates a fresh subaddress

but not in the case where you've given your current address out and before someone else transfers to that address

**Comment by nahuhh** [comment]
i understand for doge (balances), but not wow or xmr(?)

**Comment by rehrar** [comment]
Because we already show the most recently generated address on the Receive screen, I think this is sufficient, as adding another button would clutter the UI of the address book.
