### ISSUE TITLE
setup.sh automated build script issues: does not install `flutter` as expected, `cargo-ndk` fails to build

### ISSUE THREAD

**Issue by AaronFeickert** [cypherstack/stack_wallet#272]
The build script does not properly install `flutter`, as [this line](https://github.com/cypherstack/stack_wallet/blob/dfb227adfb30c34e8915a597c95e8a1d67850cee/scripts/setup.sh#L18) fails.

It may also be the case that another `source` is needed after [installing Rust](https://github.com/cypherstack/stack_wallet/blob/staging/scripts/setup.sh#L44).

**Comment by julian-CStack** [comment]
flutter version also needs to be updated in this script

**Comment by sneurlax** [comment]
Today on a new install I experienced this issue, where line 19 (`flutter doctor`) fails.  Also, `cargo-ndk` failed to build.  The documentation should be updated to note that Android Studio should be installed before the setup script it run, as well.
