### ISSUE TITLE
Add F-Droid link on website

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#290]
Please add a link on the website to take you to the fdroid repo for stack wallet. I would of not found it without searching github issues.

**Comment by rehrar** [comment]
Added.

**Comment by RokeJulianLockhart** [comment]
https://play.google.com/store/apps/details?id=com.cypherstack.stackwallet#:~:text=Icon%20image-,Stack%20Wallet,-Cypher%20Stack%20Team
