### ISSUE TITLE
12 & 24 Seed Phrases for Monero

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#292]
Please support 12 and 24 seed phrase for creating and restoring Monero wallets Some people have 12 word wallets, some have 24 word wallets for Bitcoin, Litecoin, etc and would like to use the same 12 or 24 words for every cryptocurrency wallet.

You can also use a 12 and 24 seed phrase wallet and have it converted to a 25 XMR seed phrase, look at how Coinomi does it below.

https://github.com/Coinomi/bip39-coinomi

**Comment by nahuhh** [comment]
only support core implementations - 25 and 16(soon)

**Comment by rehrar** [comment]
25 and 16 word seeds are now supported. I don't know what coinomi does but I don't think we'll be supporting if it's actually 12 and 24.
