### ISSUE TITLE
Choose Receive Amount Requested

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#294]
Please add a feature in the receiving crypto page to set how much crypto to receive and this will be added at the end of the address and in the QR code

For example. the user can set the receive amount to 22 XMR and it will request 22 XMR. If the user set the receive to 22 USD, it will request 22 worth of XMR at that time of generating the address.

**Comment by rehrar** [comment]
This is currently present, but a little hard to find. You have to click Create new QR code, and it allows you to edit these values.
