### ISSUE TITLE
Reorder Wallets Under Cryptocurrencies

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#295]
Please add a setting to reorder the wallets under each cryptocurrency on the home page

**Comment by rehrar** [comment]
For the time being, we're going to make these alphabetical. We'll look into reordering in the future.

**Comment by trymeouteh** [comment]
Alphabetical is better than having the wallets in order by creation.

**Comment by trymeouteh** [comment]
Cryptocurrencies are now sorted alphabetically! Now just the wallets under a crypto need to be sorted alphabetical.
