### ISSUE TITLE
Label Your Own Addresses

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#297]
Please have a "secondary address book" but is for your own addresses.

- To have the ability to label an address when you generate it in the receive page.
- To have the ability to change the receiving address to any address that was generated before in the receive page.
- To be able to go into your addresses menu and rename labels, remove labels or add labels
- To be able to go into your addresses menu and view all generated addresses (even ones that were never labelled)

This is also related to
https://github.com/cypherstack/stack_wallet/issues/296

**Comment by rehrar** [comment]
Added the ability to label all addresses.

**Comment by trymeouteh** [comment]
Thank you!
