### ISSUE TITLE
[feature request] automatic light/dark theme based on system settings on android

### ISSUE THREAD

**Issue by its-me-ct** [cypherstack/stack_wallet#310]
Android supports system wide light/dark mode since version 10, which also works in apps, if they support it. I very much welcome this feature, as it allows me to switch ligh/dark mode based on time of day or ambient light.

Currently Stack Wallet supports themes, but no automatic switching based on the system wide mode. The defacto standard implementation is to let the user select from a dropdown menu like this:

- Light
- Dark
- Black (OLED)
- System (Dark)
- System (Black)

Because Stack wallet also supports more creative themes like the new "Ocean Breeze", it might be a good idea to split it into two lists, so that arbitrary combinations are possible, like this:

Default Theme:

- Light
- Dark
- Black (OLED)
- Ocean Breeze

Dark Theme:

- Default
- Light
- Dark
- Black (OLED)
- Ocean Breeze

This way a user could select "Ocean Breeze" as the default theme and "Dark" as the dark one. If a user does not want automatic switching, they can eg. select "Black" as the default, and "Default" as the dark one.

The feature is only a "nice to have", but because Stack Wallet seems to care a lot about excellent UX, I think it's worth considering.

**Comment by trymeouteh** [comment]
This would be great for Mobile and desktop.

**Comment by rehrar** [comment]
This has been added.
