### ISSUE TITLE
UX/usability suggestion: skip wallet list popup when there is exactly 1 wallet

### ISSUE THREAD

**Issue by molecular** [cypherstack/stack_wallet#316]
I love stack wallet because it's very "no-bs" and everything is easily accessible.

However there is one little issue I have: 

When I select a coin from main screen, there is a little popup that slides in from the bottom that lists all the wallets for that coin. I only have one wallet. My suggestion is to skip this step and go directly to the wallet in case there is only 1 wallet in that list.

![image](https://user-images.githubusercontent.com/589745/213861079-0ce02579-daee-4cae-8945-e553b02e380d.png)

**Comment by rehrar** [comment]
I was thinking this same thing the other day! Great minds and all that.

**Comment by rehrar** [comment]
Added. Done.
