### ISSUE TITLE
UX/usability: back button

### ISSUE THREAD

**Issue by molecular** [cypherstack/stack_wallet#317]
The phones back button doesn't do what I would expect in many cases.

For example on the wallet screen, when I use the back button, I get "tap back button again to exit app". Since I use my phone in the right hand I can easily thumb the back button, but using the little back arrow on the top left requires use of my 2nd hand.

![image](https://user-images.githubusercontent.com/589745/213861212-f367d70d-0aa2-433a-aeb8-42e5de5a750e.png)

The phone's back button should do whatever the back button on top left of the screen does, in this example case: leave wallet and go back to main screen.

**Comment by nahuhh** [comment]
I think the current behavior is OK, but only when the sync mode is set to `sync only currently open wallet`, as you are confirming youd like to stop syncing.
the confirmation is absent when using the top left back arrow, should probably be added there for consistency.

when set to `sync all` or `sync only selected` - no need for the confirmation, as you arent stopping the sync 

For simplicity, i support removing the in-wallet confirmation altogether

**Comment by molecular** [comment]
Oh, it turns out I was making wrong assumptions. I though confirming "Tap back again to exit wallet" would actually **close the app**. It's not the case, it just exits the wallet and goes back to main screen, which is totally fine, yes.

> For simplicity, i support removing the in-wallet confirmation altogether

That would be perfect imo.
