### ISSUE TITLE
Monero: Issues with personal nodes

### ISSUE THREAD

**Issue by ghost** [cypherstack/stack_wallet#347]
Adding a personal Monero node shows a "connected" status but never synchronises. Sync status always shows "0.00% (Blocks to go: ?)". Copied settings directly into monerujo and immediately synchronised.

Adding a personal bitcoin node successfully syncs without issues, however, exiting a bitcoin wallet and immediately returning to it again shows the wallet as 0% synchronised, taking 20-30 seconds before reaching 100%.

Android 13, Pixel 7 Pro.
Stack wallet master & pre release versions tested.

**Comment by InnocuousFinch** [comment]
> Adding a personal Monero node shows a "connected" status but never synchronises. Sync status always shows "0.00% (Blocks to go: ?)". Copied settings directly into monerujo and immediately synchronised.
> 

Are you still having this issue? I had same problem with XMR wallets and was fixed in latest release. Although I'm on iOS TestFlight.

Haven't had bitcoin node sync issues, hitting my Fulcrum node.

**Comment by nahuhh** [comment]
@kycfree1 can you confirm that you added http:// or https://? 

stack doesnt (atm) properly report connected status of the node. (Shows connected even if the node is offline - so ignore that for now)

**Comment by nahuhh** [comment]
> if anyone else using the "--rpc-login" flag has encountered this issue

^ i wont be able to test until later today, but ill try to reproduce if someone doesn't get to it before me

**Comment by nahuhh** [comment]
![zrr046wxhnq2qfkn.jpg](https://user-images.githubusercontent.com/50635951/221412061-1b903977-c583-4960-a382-cdbdece9debc.jpg)

@rehrar it appears rpc-login isnt working
