### ISSUE TITLE
Address List Derived Addresses Path Number

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#375]
Please add the derived addresses path number for each address in the address list menu.

[![Screenshot-20230225-185314-Trebuchet.png](https://i.postimg.cc/B6CRRWZb/Screenshot-20230225-185314-Trebuchet.png)](https://postimg.cc/WFh9JHkc)

**Comment by trymeouteh** [comment]
Please also add this for the coin control menu

**Comment by rehrar** [comment]
We've added an address details screen, and it has more info. Does this solve the issue for you?

**Comment by trymeouteh** [comment]
I would like to see the derived path listed below the address on the screen without having to tap on the address to get the derived path.

And would it be possible to bring back the copy address button and show QR code button also for quick access? I do like how each address page has many details like the derived path, qr code, labels, tags, etc.

**Comment by rehrar** [comment]
The screen is already crowded enough so I believe the current way is the most acceptable.
