### ISSUE TITLE
FEATURE REQUEST: Please add support for Wownero $WOW 

### ISSUE THREAD

**Issue by mvozzo** [cypherstack/stack_wallet#40]
Hello Stack Wallet, 
It's awesome that you are launching a "Privacy Preserving" focussed wallet. Nice!

Can you please ADD support for a privacy coin called Wownero, which is a hard fork of Monero. 
I'm not a coder, but I presume the majority of the code base is similar to Monero, hence is may not be much work to add this coin.

**Wownero (WOW) - a fork of Monero**   
Homepage - https://wownero.org  
Talk to Devs - https://forum.wownero.com/

Many thanks for supporting with Privacy Coin.

**Comment by rehrar** [comment]
We're looking into it. Thanks for the suggestion!

**Comment by mvozzo** [comment]
THANK YOU @rehrar .  This is AMAZING News and I've shared this out on social media and with members of the Wownero community.   I will install it and start storing WOW on Stack Wallet!
