### ISSUE TITLE
Feature Request: Bitcoin RBF

### ISSUE THREAD

**Issue by apemithrandir** [cypherstack/stack_wallet#414]
Given the volatile fee environment in Bitcoin, it would be useful have Bitcoin RBF in the Bitcoin wallet.

https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki

I would assume RBF should be enabled by default. There will be some UX work to figure out how to incorporate it. Might be an advanced feature but could still be enabled by default when sending to allow people to speed up a transaction needed.

**Comment by rehrar** [comment]
;)
