### ISSUE TITLE
Set light/dark theme to follow system default

### ISSUE THREAD

**Issue by InnocuousFinch** [cypherstack/stack_wallet#415]
UI feature request: allow selecting a theme for light mode and a theme for dark mode, so that depending on your phone's system default settings the proper theme will be selected. 

Use case: I like the forest theme, but it’s way too bright for night time. I’d like to have the forest theme when my phone is in light mode during the day, and oled black theme for dark mode during the night.

**Comment by rehrar** [comment]
Now included
