### ISSUE TITLE
Does not recognize change address when importing wallet.

### ISSUE THREAD

**Issue by sheriff-shinetop** [cypherstack/stack_wallet#418]
Imported a BCH wallet from the Bitcoin.com app, all transactions show up and the balance is correct but for some/all (this wallet has 50+ transactions, didn't get around to checking all of them) it doesn't recognize the change output is going back to the wallet.

For example a $1 transaction with two outputs, one going to an external wallet ($0.10) and one output back to the wallet's change address ($0.90) shows up as -$1 outgoing while it's only $0.10.

One other wallet I tried this with does recognize the change addresses correctly so I have to assume Bitcoin.com properly adheres to BIP44 and the problem is in Stack Wallet.

**Comment by sheriff-shinetop** [comment]
Just noticed #330, looks like this should be working properly in the next release?

**Comment by rehrar** [comment]
This should have been fixed already many releases ago, so if you're still having an issue we did something wrong. Let me see.

**Comment by sneurlax** [comment]
I'll make sure change addresses are also added
