### ISSUE TITLE
docs to build the iOS app?

### ISSUE THREAD

**Issue by Logicwax** [cypherstack/stack_wallet#423]
since it's claimed `Stack Wallet is a fully open source cryptocurrency wallet.` how can I build this for iOS?    I see that this is Flutter-based, but is everything available to build this for iOS?    Are there plans to document the build instructions for this?

**Comment by InnocuousFinch** [comment]
I am getting close to completing the iOS build documentation. Once completed I will submit a PR to get it added to the repo. Will ping you here to let you know when that is completed.

**Comment by rehrar** [comment]
done
