### ISSUE TITLE
Bug: Opening any two XMR wallets will cause Stack Wallet to crash

### ISSUE THREAD

**Issue by InnocuousFinch** [cypherstack/stack_wallet#424]
This bug has been around for a few releases and I'm finally getting to submitting an issue for it.

I've got 3 XMR wallets in Stack. If I open one of the XMR wallets, back out to the main menu, and open another XMR wallet (can be the same one), Stack Wallet will crash 100% of the time. Doesn't matter if I wait a few minutes or do it right away.

I'm on latest TestFlight of Stack Wallet on iOS.

**Comment by Sakooooo** [comment]
happens to me without a second wallet

**Comment by realduug** [comment]
Mine crashes when setting the seed phrase.
