### ISSUE TITLE
Feature Request: Remove BTC addresses from address book and add PayNyms

### ISSUE THREAD

**Issue by InnocuousFinch** [cypherstack/stack_wallet#432]
## Problem
Static addresses should never be used in Bitcoin, as it's bad for privacy. Currently, the address book only allows for adding Bitcoin contacts with static addresses.

## Solution

1. Remove the ability for users to add static addresses as Bitcoin contacts
2. Add PayNyms to Address book for Bitcoin contacts.

**Note**: This will mean you will probably want to make it so that anytime a user sends a notification transaction to a PayNym to connect to them, that PayNym is automatically added to their BTC address and cannot be deleted (but things like name etc can be modified). This will provide the best UX for the end user, as they won't need to first connect to a PayNym, then manually add a connected PayNym to their address book. Once they connect to a PayNym, it automatically shows up in the address book as a payable BTC contact.

**Comment by rehrar** [comment]
Closed for now until we decide what to do with paynyms.
