### ISSUE TITLE
Use tor to connect to your node of choice

### ISSUE THREAD

**Issue by yoshimo** [cypherstack/stack_wallet#442]
At the moment you can only enter port and & ip adress for a node.
With full nodes running at home or in a data center you might not want to reveal its location or have to fight a changing ip adress, it is good practice to use a tor onion adress instead. You also might want to hide your identity and location from the node that serves you data

It would be good for privacy if stackwallet would offer the choice of running connections over tor.

**Comment by nahuhh** [comment]
You can

https://guides.cakewallet.com/docs/tutorials/mobile-hardening/#using-invizible-pro

step 1-6

**Comment by rehrar** [comment]
Works.

**Comment by k4r4b3y** [comment]
@rehrar when I test latest version of stack wallet (installed from fdroid) for connecting to my .onion monero node, I get no visual indicators of connection success (nor failure).  I enter my node address: http://longlongaddress.onion , and then enter Port: 18089.  And tap on "Test connection."  The tor inside Stack Wallet is active and running.  However, "Test Connection" doesn't return a positive test result, nor a negative test result.  The UI just stays there.

The same .onion address + port works for me when I try the same on feather wallet.

**Comment by nahuhh** [comment]
K4r4 did you wait long enough?

**Comment by k4r4b3y** [comment]
> K4r4 did you wait long enough?

I wait around 10 seconds.  Nothing happens on the UI, behaves as if I never tapped on "Test Connection" button.

**Comment by k4r4b3y** [comment]
I can also ping my onion restricted-rpc server I mentioned above inside tor browser, by visiting the URL: http://longlongaddress.onion/18089/getinfo

However, stack wallet is unable to use that onion restricted rpc server, as tested in the following two cases:

1) stackwallet's internal tor daemon is active, and stack wallet's tor killswitch turned ON.  The "Test Connection" is returns nothing.  Neither confirms server is reachable, nor denies.

2) stackwallet's internal tor daemon is disabled, and stack wallet's tor killswitch turned OFF.  I use Orbot to route stackwallet's connections through the Tor network.  On the same monerod restericted rpc server onion address, stackwallet's "Test Connection" this time returns "Server Unreachable".

**Comment by nahuhh** [comment]
Youre right. Looks like a regression
It worked in the version before this one iirc

**Comment by k4r4b3y** [comment]
> It worked in the version before this one iirc

Iirc, I was able to ping my restricted rpc onion server using Orbot to route tor for stackwallet, in the previous fdroid release.  But now, I can't do that either.  Nor can I use the internal tor daemon to reach my restricted rpc server.

**Comment by nahuhh** [comment]
> > It worked in the version before this one iirc
> 
> Iirc, I was able to ping my restricted rpc onion server using Orbot to route tor for stackwallet, in the previous fdroid release.  But now, I can't do that either.  Nor can I use the internal tor daemon to reach my restricted rpc server.

Same.

onion nodes appear to be completely broken now

**Comment by nahuhh** [comment]
@rehrar

**Comment by k4r4b3y** [comment]
> @rehrar when I test latest version of stack wallet (installed from fdroid) for connecting to my .onion monero node, I get no visual indicators of connection success (nor failure). I enter my node address: http://longlongaddress.onion , and then enter Port: 18089. And tap on "Test connection." The tor inside Stack Wallet is active and running. However, "Test Connection" doesn't return a positive test result, nor a negative test result. The UI just stays there.
> 
> The same .onion address + port works for me when I try the same on feather wallet.

@rehrar @nahuhh stackwallet fdroid version 2.1.4 fixes this.  I am able to connect to my onion node within Stack wallet's tor activation + node selection UI.  Thanks rehrar!
