### ISSUE TITLE
Payments & Mixing via Wabisabi

### ISSUE THREAD

**Issue by yoshimo** [cypherstack/stack_wallet#448]
https://github.com/zkSNACKs/WabiSabi/ is a protocol for Centrally Coordinated Coinjoins with Variable Amounts
To avoid the hot topic of https://twitter.com/wasabiwallet/status/1503091503207432193  you might want to spin up your own coordinator and make use of the same feature that the btcpayserver plugin uses to use more than one coordinator.

```
https://bitcoinmagazine.com/technical/how-nostr-can-improve-bitcoin-privacy 
https://blog.wasabiwallet.io/wasabiwalletxbtcpayserver/
https://github.com/zkSNACKs/WasabiDoc/pull/946/files

```
Variable amounts make it less obvious that mixing was used and help to avoid trouble.

**Comment by rehrar** [comment]
We have no plans to implement WabiSabi. Especially after this twitter thread by SethForPrivacy. https://twitter.com/sethforprivacy/status/1642887164752019459 If the underlying tech changes in considerable way we can take another look.
