### ISSUE TITLE
Missing documentation on which coins are supported

### ISSUE THREAD

**Issue by jahway603** [cypherstack/stack_wallet#479]
Missing documentation on which coins are supported. This repo's README.md shows "5 Different cryptocurrencies" yet the Google PlayToy store shows "10 Different cryptocurrencies" & neither contain a list of which coins are supported by this wallet.

**Comment by detherminal** [comment]
@rehrar I think we must push from staging branch to main branch so this issue can be solved.

**Comment by detherminal** [comment]
This issue can be closed as [this pr](https://github.com/cypherstack/stack_wallet/pull/492) completed the request @rehrar
