### ISSUE TITLE
Playstore image at top of README.md yields a 404 error

### ISSUE THREAD

**Issue by jahway603** [cypherstack/stack_wallet#498]
The [Playstore image](https://bluewallet.io/img/play-store-badge.svg) used at top of README.md yields a 404 error. Suggestion is to include the image in this repo and use it locally so this won't happen again.

**Comment by detherminal** [comment]
After pushing from staging to main, this should be resolved. @rehrar

**Comment by jahway603** [comment]
Thanks. Commit https://github.com/cypherstack/stack_wallet/commit/87bce5bb697b7fcc03aee23da00526af1001a5b3 resolved this.
