### ISSUE TITLE
Request Scrolling in AppImage

### ISSUE THREAD

**Issue by NunyaBiznus** [cypherstack/stack_wallet#507]
Would like to request that scrolling be added to a few screens in the Linux AppImage. On these screens buttons can be cut off or totally not visible until the window is manually resized. The screens I've noticed this issue with are:

- New Stack
![NewStack-SS](https://user-images.githubusercontent.com/111243845/235186519-2716fe3e-4108-4190-be28-b3bede58f4c4.png)

- Add Wallet
![AddWallet-SS](https://user-images.githubusercontent.com/111243845/235186601-8f8d568b-4fd9-423d-babe-e70207c476ce.png)

- Wallet Recovery
![MoneroRecovery-SS](https://user-images.githubusercontent.com/111243845/235186712-e20b4bf0-86e7-48f8-8dd7-aed10b3c5945.png)

**Comment by alextecplayz** [comment]
Same issue here. Can't even restore my backup because some of the wallets and buttons are cut off.
