### ISSUE TITLE
AppImage: Details of transaction not visible

### ISSUE THREAD

**Issue by Obamium69** [cypherstack/stack_wallet#509]
```
Systeminfo: 
OS: EndeavourOS x86_64
Kernel: 6.2.13-zen-1-zen
DE: KDE Plasma 5.27.4
WM: KWin (X11)
CPU: Intel(R) Core(TM) i7-9700K (8) @ 4.9 GHz
GPU: NVIDIA GeForce RTX 3080 12GB
```
When i try to view the details of a transaction only a grey box is displayed. 

![grafik](https://user-images.githubusercontent.com/61025357/235314110-aa323319-0cc8-4890-96c3-ff67040abfee.png)

If you need more information please let me know.

**Comment by rehrar** [comment]
Which coin was this for? What version of Stack is it?

**Comment by Obamium69** [comment]
The coin is Monero and the version is 1.7.4

**Comment by Obamium69** [comment]
There also seems to be an issue with my monero wallet, so that i can't open it
![grafik](https://user-images.githubusercontent.com/61025357/235972445-4d456d55-57d1-4435-9b23-d6ff4934ff38.png)
Should i open a new issue?

**Comment by sneurlax** [comment]
> There also seems to be an issue with my monero wallet, so that i can't open it ![grafik](https://user-images.githubusercontent.com/61025357/235972445-4d456d55-57d1-4435-9b23-d6ff4934ff38.png) Should i open a new issue?

Yes, please open a separate issue for a separate problem
