### ISSUE TITLE
App on iOS crashes when trying to open Wownero wallet

### ISSUE THREAD

**Issue by mondsen** [cypherstack/stack_wallet#526]
Hi,

with the latest app version on iOS Stack wallet crashes when tapping on the Wownero wallet I have. The other wallet (Doge) is working fine. 

Unfortunately the debug log does not provide any help. There are no issues, only INFO messages. Any idea how to debug this?

**Comment by rehrar** [comment]
This is fixed with the latest release (v2.1.0)
