### ISSUE TITLE
Plugin/Extension Coin feature

### ISSUE THREAD

**Issue by trymeouteh** [cypherstack/stack_wallet#541]
I would like to suggest a system to allow stack wallet to accwpt hundreds of cryptocurrencies by having a plugin system. Allowing anyone to add a coin into stack wallet.

- Documentation on how to create coins
   - Sync with chain
   - Display balance
   - convert balance to fiat
   - send
   - recieve
   - coin control
   - address management
   - seed phrase
   - node settings
   - block explorer settings
   - hardware wallet integration
- The ability to import coins from ZIP files
- A official repository of trusted coins that can be downloaded, imported and updated automatically
- Ability to host your own coin plugin respitory using github, gitlab, gitea or forgejo. This will allow others to import more coins from 3rd party repositories and also recieve updates to these coins

If Trezor hardware wallet support also gets added to stack, more coine can easily be managed with a easy to use open source wallet.

And with a plugin system, developers of a cryptocurrency do not need to develop an entire wallet, just a plugin to have it supported in stack wallet. Stack wallet is written in dark which allows it to be compiled on desktop and mobile, allowing even new coins to be supported on a FOSS wallet on all devices early on.

**Comment by rehrar** [comment]
At the moment this is not feasible for us as it would require a significant refactor in terms of how the wallet functions, which we do not have the resources to do at the moment. Nice idea for a fresh wallet though.
