### ISSUE TITLE
Failed to restore Bitcoin Cash Wallet

### ISSUE THREAD

**Issue by JettScythe** [cypherstack/stack_wallet#542]
As the title states, having issues restoring a bitcoin cash wallet from seed. 
"Failed to process CachedElectrumX.getTransaction(): HandshakeException: Connection terminated during handshake"

Tested on pic related 
![image](https://github.com/cypherstack/stack_wallet/assets/37233887/1d515d1d-5726-4d40-96af-027d509d91c6)
![image](https://github.com/cypherstack/stack_wallet/assets/37233887/9dc265ca-fcd1-4d58-bb69-762610a0bdce)

**Comment by sneurlax** [comment]
Can you retry restoration and see if it works or if there same error message still occurs when you try?

**Comment by JettScythe** [comment]
Can confirm it is now working :)
