### ISSUE TITLE
Bug: Transaction Failed: 'Null Check operator used on a null value' (eCash XEC)

### ISSUE THREAD

**Issue by Kronkmeister** [cypherstack/stack_wallet#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/cypherstack/stack_wallet/assets/49569383/0544f19c-abb2-43be-a499-085695807d8a)

Transaction failure when trying to send XEC. In this case it were coins that were noet yet confirmed (0-conf). 
Trying it again after a few confirmations did not result in this issue. However, this is just a wild guess.

thanks

### Expected Behavior

Transaction going through

### Reproduce Steps

1. Receive XEC to wallet address
2. Send XEC to another wallet while still not confirmed

### Environment

- Operating system and version: Android version 11
- Device platform and version: FP3 (Fairphone)
- Real device or emulator/simulator: Real Mobile Device

### Further Information

for further questions shoot Koush a message on telegram or reach out in the eCash/Stack wallet group 

t.me/eKoush

**Comment by julian-CStack** [comment]
I attempted to reproduce this but chained zero conf sends didn't give me any trouble. The only difference I know of was using smaller amounts of 40-50 XEC but that shouldn't matter I don't think.
