### ISSUE TITLE
Bug: Confirmed sent anonymized FIRO transactions never change from "Sending" state.

### ISSUE THREAD

**Issue by danrmiller** [cypherstack/stack_wallet#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Confirmed sent anonymized FIRO transactions never change from "Sending" state. Block Height stays "Pending" despite thousands of confirmations. Reproducible. 

### Expected Behavior

Should go to "Sent" and show the block height it is confirmed at.

### Reproduce Steps

Send anonymized funds.

### Environment

- Android
- Samsung Galaxy Note

**Comment by julian-CStack** [comment]
should be fixed
