### ISSUE TITLE
Slow and failing import

### ISSUE THREAD

**Issue by monsterbitar** [cypherstack/stack_wallet#699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After entering seed words for a wallet with a long transction history (~1500 transactions), I am shown a "Restoring wallet" dialog and is aked not to exit the screen.

This process continues for almost half an hour, then failed with "get transaction returned null for ...".

During this process, my seed words are displayed in the background.

Attempting to go through the process a second time caused it to fail earlier, with the same error message, but different transaction hash: `getTransaction(..) returned null response`

### Expected Behavior

I expected that the wallet would recognize the seed words upon finding the first transaction, thereby knowing that this wallet has history.

I then expected that it would import that history in the background, rather than in the foreground.

I also expected it to show me some kind of status indicating how far long the process it has come.

### Reproduce Steps

I can't confirm if this is reproducable with any other seed, but the process is essentially:

- add a new wallet
- choose to import from seed 
- provide a seed with a rich and long history

### Environment

- Operating system and version: android... 10? I think 10, not sure.
- Device platform and version: oukitel WP something something form a few years back.
- Real device or emulator/simulator: real device.

**Comment by monsterbitar** [comment]
For clarity, on my third try I copied the transaction hash to ensure it wasn't trying to look up something it shouldn't be looking up, and the transaction hash is for a valid transaction that is part of my wallet history, but coincidentally it seems to be a transaction one step out:

https://blockchair.com/bitcoin-cash/transaction/a3ce9989a91ac554ecb9a0121ff96775e0c19a907d050ec69b80b66291124a4d

where my wallet did the transaction that lead to this point here:

https://blockchair.com/bitcoin-cash/transaction/4ca789a8e09ac5ded75eea66600a2504688af573cb0b2fbf56154eabd511a815?o=1

The transaction it failed on is a funding transaction for an anyhedge contract, thought given that it is one step removed from the wallet and that the anyhedge contracts are just P2SH addresses like any other I don't see how this would lead to a failure here.

**Comment by monsterbitar** [comment]
... on the fourth try it took about 5 seconds and then said "you can use your wallet now".

**Comment by rehrar** [comment]
Do these issues persist with our recent big refactors and bug fixes (v2.1.0)? @serrq @monsterbitar
