### ISSUE TITLE
Fusion process is too much slow

### ISSUE THREAD

**Issue by serrq** [cypherstack/stack_wallet#703]
I would like to follow the fusion process (BCH) in background, from the notification panel, in real time. The user should be able to close this window.

![1000097126](https://github.com/cypherstack/stack_wallet/assets/113377431/2b0c06ce-c459-41d4-a27c-5d373a4dfe46)

![1000097123](https://github.com/cypherstack/stack_wallet/assets/113377431/dcd84178-ac3d-4bbf-ad43-21778cbab43a)

**Comment by sneurlax** [comment]
Running in the background is not feasible due to platform restrictions (eg. iOS).  We cannot make the fusion process go any faster, unfortunately.  The process is also constrained by available liquidity
