### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by MyEcoria** [cypherstack/stack_wallet#708]
Hello, I followed the doc to build the code but when I execute the `flutter build apk` command, I get this error 🥲
![Screenshot_2023-12-01-13-55-01-427_com sonelli juicessh](https://github.com/cypherstack/stack_wallet/assets/103332030/a81f3411-9211-4593-a905-e0a40b5aeecc)

**Comment by sneurlax** [comment]
Can you try compiling flutter_libmonero again?

After cloning stack_wallet, cd into stack_wallet/crypto_plugins/flutter_libmonero, then follow its README.md to build (`cd stack_wallet/crypto_plugins/flutter_libmonero/scripts/linux/build_all.sh`)

**Comment by MyEcoria** [comment]
Yes, thank you, over time I finally understood and managed to compile it thank you 🙃

**Comment by Shourya742** [comment]
Hello @MyEcoria ,I'm facing the same issue. Could you share how you resolved it?
