### ISSUE TITLE
Desktop: toasts invisibly block clicks across screen width

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/stack_wallet#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Toasts cover the top of the app area with an invisible unclickable area.  The image below shows the area (cannot click the "back" nor "Wallet Keys" buttons until the toast recedes):

![Screenshot from 2024-01-22 12-17-55](https://github.com/cypherstack/stack_wallet/assets/4107993/bb3bdd6e-f77e-45e3-8a37-f7cbdcedf0fb)

Not tested on mobile, but I assume as toasts probably fill most (if not all) of the device screen's width, I don't think that this will apply to mobile platforms or be as noticable.

### Expected Behavior

You should be able to click buttons not obscured by the body of the toast: the invisible padding to the sides should be clickthrough.

### Reproduce Steps

Make a toast on desktop and attempt to click an element to either side of the toast while it's still showing.

### Environment

- Operating system and version: Ubuntu 20.04

**Comment by julian-CStack** [comment]
Limitation of the current lib being used for in app slide down notifications. Its possible to dismiss it faster by dragging/swiping it up.
One day we'll find a better lib or come up with our own solution
