### ISSUE TITLE
Bug: Wownero wallet refuses to show correct Full Balance

### ISSUE THREAD

**Issue by MakisChristou** [cypherstack/stack_wallet#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When loading my mnemonic of an old WOW wallet the older transactions show up and are reflected in the Full balance. I made 2 more recent txs and for some reason only 1 is shown in the list and none are reflected in the Full Balance. What is even weirder is that if I delete and re-import the wallet after its done scanning it correctly shows all txs in the list and the correct Full Balance. But after a while (maybe I close and reopen the app on another day) it reverts to the state I mentioned. 
![wownero_issue](https://github.com/cypherstack/stack_wallet/assets/39631552/d0de56bd-f4e5-49ad-996c-1d25b9151b65)

### Expected Behavior

All txs should show up in the list and the correct Full Balance should be shown.

### Reproduce Steps

Honestly not sure.

### Environment

- Operating system and version: IOS 17.2.1
- Device platform and version: Iphone 14 Pro
- Real device or emulator/simulator: Real Device
- Stack Wallet Version: 1.9.2

**Comment by rehrar** [comment]
We did a big refactor of both Monero and Wownero. Is this still the case?
