### ISSUE TITLE
Remove SYSTEM_ALERT_WINDOW permission

### ISSUE THREAD

**Issue by jermanuts** [cypherstack/stack_wallet#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This permission makes it possible to draw over other apps which is security risk and I don't think Stack Wallet makes use of that permission anyways, so having it is pointless. If you want some kind of protection and prevent apps from drawing over Stack Wallet, you could use [HIDE_OVERLAY_WINDOWS](https://developer.android.com/reference/android/Manifest.permission#HIDE_OVERLAY_WINDOWS) which will increase Stack Wallet security.

### Expected Behavior

Stop using this permission and use the other recommended permission for enhanced security.

### Reproduce Steps

.

### Environment

.

### Further Information

https://code.briarproject.org/briar/briar/-/issues/956#note_20639 

https://blog.nviso.eu/2021/05/11/new-malware-family-now-also-targets-belgian-financial-apps/

**Comment by julian-CStack** [comment]
We don't use that permission https://github.com/cypherstack/stack_wallet/blob/main/android/app/src/main/AndroidManifest.xml
Its possible some library uses it. Could you point to where you've found it being used?

**Comment by jermanuts** [comment]
https://reports.exodus-privacy.eu.org/en/reports/com.cypherstack.stackwallet/latest/

Play Store

![image](https://github.com/cypherstack/stack_wallet/assets/109705802/069a5974-e1ab-42e7-b5da-14fdce615673)

**Comment by sneurlax** [comment]
@julian-CStack said:

> I've tracked the permission referenced in https://github.com/cypherstack/stack_wallet/issues/796 to flutter_libepiccash here:
https://github.com/cypherstack/flutter_libepiccash/blob/4280d6947e69c995d7c5c71e75111d5f7161dc6d/android/src/main/AndroidManifest.xml#L4
> and
> https://github.com/cypherstack/flutter_libepiccash/blob/3dc6016960e5c715c532427089af3eadfce0e476/example/android/app/src/main/AndroidManifest.xml#L4

**Comment by julian-CStack** [comment]
Should not be there in next release
