### ISSUE TITLE
Linux desktop build_all script doesn't build frostdart

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/stack_wallet#806]
`script/linux/build_all.sh` doesn't build frostdart (or fails to)

It should probably do so

**Comment by Likho** [comment]
@sneurlax What error are you getting? I was getting a libssl error - doing `sudo apt-get install libssl-dev` resolved the ssl issue for me

**Comment by sneurlax** [comment]
> @sneurlax What error are you getting? I was getting a libssl error - doing `sudo apt-get install libssl-dev` resolved the ssl issue for me

We may need to add that to the docs: https://github.com/cypherstack/stack_wallet/pull/801

I was referring to how scripts/linux/build_all.sh doesn't build frostdart, but that's just on `main`--`staging` already has it (https://github.com/cypherstack/stack_wallet/blob/staging/scripts/linux/build_all.sh#L18-L19), so I think this can be closed.

**Comment by sneurlax** [comment]
> @sneurlax What error are you getting? I was getting a libssl error - doing `sudo apt-get install libssl-dev` resolved the ssl issue for me

PS the docs do include libssl-dev as a dep: https://github.com/cypherstack/stack_wallet/pull/801/files#diff-af936db1633489b017d1e45a55448545529ebc354aeb40eda83af5db7317a6e1R51
