### ISSUE TITLE
Bug: Wallet doesn't support Monero payment links (thinks it's invalid when there's an amount included)

### ISSUE THREAD

**Issue by tohrxyz** [cypherstack/stack_wallet#826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I scan a QR code with XMR address and amount included, the wallet extracts only the address part and not the amount into the fields when sending a tx.

When I paste the payment link directly into the address link, it says it's invalid address.

**Payment link example**:
monero:88FTtUb43DdUiRBxxxxx...?tx_amount=0.213xxxx

### Expected Behavior

It should extract and pre-insert the amount from qr code, so that user doesn't need to type out the amount manually.

Also it should parse the payment link and paste appropriate parts into the fields.

### Reproduce Steps

1. scan a qr code with amount of xmr included
2. only extracts address

1. paste payment link into address field directly
2. says it's invalid address

### Environment

- Operating system and version: iOS 17.1
- Device platform and version: iPhone
- Real device or emulator/simulator: real phone

**Comment by rehrar** [comment]
Fixed!

**Comment by sneurlax** [comment]
Close by #935
