### ISSUE TITLE
Bug: Dark mode QR scanning

### ISSUE THREAD

**Issue by stnby** [cypherstack/stack_wallet#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In dark mode of the app generated QR code (specifically in receive section) is impossible to scan by many commercial QR code scanners (crypto ATMs).

### Expected Behavior

Generated QR code regardless of the theme should be a standard black code on white background (white border included) https://en.wikipedia.org/wiki/QR_code

### Reproduce Steps

Make sure app is in dark mode. Click "Receive" and attempt to scan generated QR code with an industrial scanner.

### Environment

- Operating system and version: Android
- Device platform and version: 1.10.2 (2214)

**Comment by rehrar** [comment]
This has been fixed in 2.1.2
