### ISSUE TITLE
Bug: I can't send to a connected paynym

### ISSUE THREAD

**Issue by 4rkad** [cypherstack/stack_wallet#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've connected to a paynym with a notification tx. After this tx is confirmed I tried several times send sats to the paynym without success. You can see in pictures the "preview" button is not in black and you can't fo forward

![1](https://github.com/cypherstack/stack_wallet/assets/55397917/6dd93d56-e09b-4d97-b131-56312135bb5e)
![3](https://github.com/cypherstack/stack_wallet/assets/55397917/c92b2147-520b-498c-897a-84a785ddc245)
![2](https://github.com/cypherstack/stack_wallet/assets/55397917/08d4279c-107a-4a12-8716-a677efdd3fbc)

### Expected Behavior

I expect to go to preview screen and send the tx

### Reproduce Steps

I'm in testnet. 
I have several utxos (no blocked)
I have connected to a paynym
I tried to send to paynym with no success

### Environment

- Operating system and version: GraphenOS (last version)
- Device platform and version: Pixel 6
- Real device or emulator/simulator: Real device

**Comment by sneurlax** [comment]
PayNym backend servers are probably down following the Samourai takedowns, see https://securityboulevard.com/2024/06/profiling-the-recently-seized-samourai-cryptocurrency-mixer-service-an-analysis/

**Comment by 4rkad** [comment]
[Paynym.is](https://paynym.is/) still working
I have tested in Sparrow and works perfectly. In Bluewallet is working too.
I had problems with the last Stack Duo update. Before it worked.

**Comment by 4rkad** [comment]
Paynym.is still working
in Sparrow is working perfectly
The problem is the last update

-------- Original Message --------

**Comment by julian-CStack** [comment]
Fixed. Will be pushed shortly and will be in next release
