### ISSUE TITLE
Feature request: display confirmation amount instead of block height in Monero transaction details UI 

### ISSUE THREAD

**Issue by k4r4b3y** [cypherstack/stack_wallet#913]
The number of confirmations, rather than the exact block height a monero transaction gets in, is important.  I always find the block height display useless for the transaction details UI, and always wonder about the number of confirmations my monero transactions get.

**Proposal:** display confirmation number, like Feather Wallet.  1/10 confirmation, 2/10 confirmation.  And after 10/10 confirmation, display an infinity symbol, or simply, "confirmation complete".  This change concerns the Monero wallet transaction details UI inside stack wallet.

**Comment by julian-CStack** [comment]
Should be in next release. Added https://github.com/cypherstack/stack_wallet/pull/939
