### ISSUE TITLE
bug: [Campfire desktop] First startup shows black screen

### ISSUE THREAD

**Issue by justanwar** [cypherstack/stack_wallet#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upon first startup on macOS, Campfire shows a black window

### Expected Behavior

Campfire Desktop for macOS starts successfully.

### Reproduce Steps

1. Download macOS Campfire from https://github.com/firoorg/campfire/releases/tag/v2.0.0
2. Start Campfire
3. A window titled Campfire should appear but with black contents
4. Restarting fixes this

### Environment

- Apple M1 iMac
- macOS 14.5 Sonoma

### Further Information

![image](https://github.com/user-attachments/assets/06772749-bd02-4fcd-af1b-ee6f383e4e0d)

**Comment by julian-CStack** [comment]
Should be handled now
