### ISSUE TITLE
Bug: [Campfire Desktop] Exit button does not work

### ISSUE THREAD

**Issue by justanwar** [cypherstack/stack_wallet#946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking Exit button does not close the wallet.

### Expected Behavior

Clicking Exit button closes the wallet.

### Reproduce Steps

Click Exit button.

### Environment

- Windows 10 22H2
- Campfire 2.0.0
- build 40, commit `aeb7de8d90c29e2787eadbb778383f5f31abc72a`
- Firo build commit `b654bf4488357c8a104900e11f9468d54a39f22b`

**Comment by julian-CStack** [comment]
Should be addressed in next release. Please reopen this issue if it happen again in the next release and we'll dig deeper.

**Comment by sneurlax** [comment]
Resolved by ce1b1f0ffb90207ba07c2ebc13fabde5804613d1
