### ISSUE TITLE
Cannot import standard wownero 25 word seed phrases

### ISSUE THREAD

**Issue by Cypher-Stack** [cypherstack/stack_wallet#99]
The only option is for 14 word seed phrases for importing wownero keys.

**Comment by mvozzo** [comment]
> The only option is for 14 word seed phrases for importing wownero keys.
 
Wownero is a fork of Monero meaning the code is nearly identical. 
Stack Wallet currently supports Monero 25 word seed phrase imports, hence, this may be a relatively quick update. 
This feature will allow the Wownero community to migrate Desktop Wallets and CLI Wallets into Stack Wallet.  
Please add this request to the roadmap. Many thanks.

**Comment by sneurlax** [comment]
Closed by #208
