### ISSUE TITLE
Bug: Unable to use local XMR node through monerod

### ISSUE THREAD

**Issue by GhostDog98** [cypherstack/stack_wallet#996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When connecting to a locally hosted monero node, i see the following traffic:
Stack sends SYN to server
Server responds with [RST, ACK]

Stack wallet says server is offline.
My cmdline options for my server are:
`./monerod --restricted-rpc --rpc-login redacted:redacted --data-dir ./`

And my node details are:
Node name: test
Url: http://192.168.0.123
Port: 18081
Login: redacted
Password: redacted

On the server, I have ports 18081, 18080, and 18089 set to ALLOW. Both the devices are on the same subnet and can clearly communicate, as I can contact a web server hosted on the same host.

### Expected Behavior

I put in the details and it works.

### Reproduce Steps

Run a node using monerod:
`./monerod --restricted-rpc --rpc-login redacted:redacted --data-dir ./`
Open up ports 18080, 18081, and 18089 using `ufw allow <port>`
Connect via stack wallet
Stack wallet fails to connect

### Environment

Server Env:
- Arch linux x86_64

Stack env:
- Build number 2243, version 2.1.4

**Comment by sneurlax** [comment]
This is probably related to RPC authentication: https://github.com/cypherstack/stack_wallet/issues/981

**Comment by sneurlax** [comment]
Been working on this, RPC authentication has just been a stumbling-block

**Comment by GhostDog98** [comment]
> This is probably related to RPC authentication: #981

I believe this is a separate issue, as when running the server using `./monerod --data-dir ./` it still fails, and i am never getting a prompt for the certificate, which suggests a failure earlier in the connection attempt.
Here's some more diagnostics should they help:
- ping from client to server returns consistently, showing the ip is reachable
- ping from server to client returns consistently
- I can reach other open ports (e.g. 80, 443, 8080) from the client

Currently waiting for monerod to fully sync with the chain, i'll run an nmap after it does...

**Comment by GhostDog98** [comment]
Ended up fixing my issue, twas a skill issue afterall;
`./monerod --restricted-rpc --rpc-bind-port 18081 --rpc-bind-ip <local ipv4 address> --confirm-external-bind --rpc-login <username>:<login> --data-dir ./` is the command you want to use if you are communicating over local network.
